CSanquer\FakeryGenerator\Model\Column:
    exclusion_policy: ALL
    accessor_order: custom
    access_type: public_method
    custom_accessor_order: [name, value, convertMethod, columns]
    properties:
        name:
            type: string
            expose: true
        value:
            type: string
            expose: true
        convertMethod:
            type: string
            expose: true
        columns:
            type: array<string, CSanquer\FakeryGenerator\Model\Column>
            expose: true
            xml_map:
                inline: false
                key_attribute_name: name
                entry_name: column
