CSanquer\FakeryGenerator\Model\Config:
    constraints:
        - Callback: [validateLocale]
    properties:
        locale:
            - Locale: ~
            - NotBlank: ~
            
        seed:
            - Type:
                type: integer
            - Range:
                min: 1
            - NotBlank: ~

        maxTimestamp:
            - DateTime: ~
            
        className:
            - Type:
                type: string
            - Length:
                min: 2
            - NotBlank: ~

        formats:
            - All:
                - Choice: 
                    callback: [ \CSanquer\FakeryGenerator\Dump\DumpManager, getAvailableFormatsForValidation]
            - Count:
                min: 1
                minMessage: "You must specify at least one file format."
                
        fakeNumber:
            - Type:
                type: integer
            - NotBlank: ~

        csvDialect:
            - Valid: ~

        variables:
            - All:
                - Type:
                    type: CSanquer\FakeryGenerator\Model\Variable
            - Valid: 
                traverse: true
                
        columns:
            - All:
                - Type:
                    type: CSanquer\FakeryGenerator\Model\Column
            - Count:
                min: 1
                minMessage: "You must specify at least one column."
            - Valid: 
                traverse: true
            
        
CSanquer\FakeryGenerator\Model\Column:
    properties:
        name:
            - Type:
                type: string
            - Length:
                min: 2
            - NotBlank: ~

        value:
            - Type:
                type: scalar
                
        convertMethod:
            - Type:
                type: string
            - Choice: 
                callback: [\CSanquer\FakeryGenerator\Helper\Converter, getAvailableConvertMethods]
            
        columns:
            - All:
                - Type:
                    type: CSanquer\FakeryGenerator\Model\Column
            - Valid: 
                traverse: true
    

CSanquer\FakeryGenerator\Model\Variable:
    constraints:
        - Callback: [validateMethod]
    properties:
        name:
            - Type:
                type: string
            - Length:
                min: 2
            - NotBlank: ~

        method:
            - Type:
                type: string
            - NotBlank: ~

        methodArguments:
            - Type:
                type: array

        unique:
            - Type:
                type: boolean
        optional:
            - Type:
                type: float
            - Range:
                min: 0.0
                max: 1.0

        maxTimestamp:
            - DateTime: ~
    
CSanquer\ColibriCsv\Dialect:
    properties:
        translit:
            - Choice:
                choices:  ['translit', 'ignore', null]

        eol:
            - Choice:
                choices:  ["\n", "\r\n", "\r"]

        encoding:
            - Type:
                type: string

        enclosingMode:
            - Choice:
                choices: ['all', 'minimal', 'nonnumeric']

        enclosure:
            - Type:
                type: string
            - NotBlank: ~

        escape:
            - Type:
                type: string
            - NotBlank: ~

        escapeDouble:
            - Type:
                type: boolean

        delimiter:
            - Type:
                type: string
            - NotBlank: ~

        useBom:
            - Type:
                type: boolean

        trim:
            - Type:
                type: boolean

        forceEncodingDetection:
            - Type:
                type: boolean

        skipEmptyLines:
            - Type:
                type: boolean

        