<?php

namespace CSanquer\FakeryGenerator\Test\Model;

use CSanquer\FakeryGenerator\Model\ColumnConfig;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-28 at 18:09:00.
 */
class ColumnConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ColumnConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ColumnConfig;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::getConvertMethod
     * @todo   Implement testGetConvertMethod().
     */
    public function testGetConvertMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::setConvertMethod
     * @todo   Implement testSetConvertMethod().
     */
    public function testSetConvertMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::getColumnConfigs
     * @todo   Implement testGetColumnConfigs().
     */
    public function testGetColumnConfigs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::setColumnConfigs
     * @todo   Implement testSetColumnConfigs().
     */
    public function testSetColumnConfigs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::addColumnConfig
     * @todo   Implement testAddColumnConfig().
     */
    public function testAddColumnConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::removeColumnConfig
     * @todo   Implement testRemoveColumnConfig().
     */
    public function testRemoveColumnConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::getAvailableConvertMethods
     * @todo   Implement testGetAvailableConvertMethods().
     */
    public function testGetAvailableConvertMethods()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::generateValues
     * @todo   Implement testGenerateValues().
     */
    public function testGenerateValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\ColumnConfig::replaceVariable
     * @todo   Implement testReplaceVariable().
     */
    public function testReplaceVariable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
