<?php

namespace CSanquer\FakeryGenerator\Test\Model;

use CSanquer\FakeryGenerator\Model\Column;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-28 at 18:09:00.
 */
class ColumnTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Column
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Column;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::getConvertMethod
     * @todo   Implement testGetConvertMethod().
     */
    public function testGetConvertMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::setConvertMethod
     * @todo   Implement testSetConvertMethod().
     */
    public function testSetConvertMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::getColumns
     * @todo   Implement testGetColumns().
     */
    public function testGetColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::setColumns
     * @todo   Implement testSetColumns().
     */
    public function testSetColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::addColumn
     * @todo   Implement testAddColumn().
     */
    public function testAddColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::removeColumn
     * @todo   Implement testRemoveColumn().
     */
    public function testRemoveColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::getAvailableConvertMethods
     * @todo   Implement testGetAvailableConvertMethods().
     */
    public function testGetAvailableConvertMethods()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::generateValues
     * @todo   Implement testGenerateValues().
     */
    public function testGenerateValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\Column::replaceVariable
     * @todo   Implement testReplaceVariable().
     */
    public function testReplaceVariable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
