<?php

namespace CSanquer\FakeryGenerator\Test\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-28 at 18:09:19.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getLocale
     * @todo   Implement testGetLocale().
     */
    public function testGetLocale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setLocale
     * @todo   Implement testSetLocale().
     */
    public function testSetLocale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::hasSeed
     * @todo   Implement testHasSeed().
     */
    public function testHasSeed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::generateSeed
     * @todo   Implement testGenerateSeed().
     */
    public function testGenerateSeed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getSeed
     * @todo   Implement testGetSeed().
     */
    public function testGetSeed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setSeed
     * @todo   Implement testSetSeed().
     */
    public function testSetSeed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getClassName
     * @todo   Implement testGetClassName().
     */
    public function testGetClassName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getClassNameLastPart
     * @todo   Implement testGetClassNameLastPart().
     */
    public function testGetClassNameLastPart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setClassName
     * @todo   Implement testSetClassName().
     */
    public function testSetClassName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::addFormat
     * @todo   Implement testAddFormat().
     */
    public function testAddFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::removeFormat
     * @todo   Implement testRemoveFormat().
     */
    public function testRemoveFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::hasFormat
     * @todo   Implement testHasFormat().
     */
    public function testHasFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getFormats
     * @todo   Implement testGetFormats().
     */
    public function testGetFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setFormats
     * @todo   Implement testSetFormats().
     */
    public function testSetFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getFakeNumber
     * @todo   Implement testGetFakeNumber().
     */
    public function testGetFakeNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setFakeNumber
     * @todo   Implement testSetFakeNumber().
     */
    public function testSetFakeNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getCsvDialect
     * @todo   Implement testGetCsvDialect().
     */
    public function testGetCsvDialect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setCsvDialect
     * @todo   Implement testSetCsvDialect().
     */
    public function testSetCsvDialect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::createCsvWriter
     * @todo   Implement testCreateCsvWriter().
     */
    public function testCreateCsvWriter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getColumn
     * @todo   Implement testGetColumn().
     */
    public function testGetColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getColumns
     * @todo   Implement testGetColumns().
     */
    public function testGetColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setColumns
     * @todo   Implement testSetColumns().
     */
    public function testSetColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::addColumn
     * @todo   Implement testAddColumn().
     */
    public function testAddColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::removeColumn
     * @todo   Implement testRemoveColumn().
     */
    public function testRemoveColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getVariables
     * @todo   Implement testGetVariables().
     */
    public function testGetVariables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::getVariable
     * @todo   Implement testGetVariable().
     */
    public function testGetVariable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::setVariables
     * @todo   Implement testSetVariables().
     */
    public function testSetVariables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::addVariable
     * @todo   Implement testAddVariable().
     */
    public function testAddVariable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::removeVariable
     * @todo   Implement testRemoveVariable().
     */
    public function testRemoveVariable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Spyrit\Datalea\Faker\Model\Config::generateColumns
     * @todo   Implement testGenerateColumns().
     */
    public function testGenerateColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
