<?php

namespace CSanquer\FakeryGenerator\Test\Model;

use CSanquer\FakeryGenerator\Model\VariableConfig;

/**
 * VariableConfigTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-13 at 08:23:50.
 * 
 * @author Charles Sanquer <charles.sanquer@gmail.com>
 */
class VariableConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var VariableConfig
     */
    protected $variableConfig;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->variableConfig = new VariableConfig();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::getName
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::getVarName
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::setName
     * 
     * @dataProvider providerGetSetName
     */
    public function testGetSetName($name, $expected)
    {
        $this->assertInstanceOf('\\CSanquer\\FakeryGenerator\\Model\\VariableConfig', $this->variableConfig->setName($name));
        $this->assertEquals($expected, $this->variableConfig->getName());
        $this->assertEquals('%'.$expected.'%', $this->variableConfig->getVarName());
    }

    public function providerGetSetName()
    {
        return array(
            array('firstname', 'firstname'),
            array('firstname%;', 'firstname'),
        );
    }
    
    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::getMethod
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::setMethod
     * @todo   Implement testSetMethod().
     */
    public function testSetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::getMethodArguments
     * @todo   Implement testGetMethodArguments().
     */
    public function testGetMethodArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::hasMethodArguments
     * @todo   Implement testHasMethodArguments().
     */
    public function testHasMethodArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::setMethodArguments
     * @todo   Implement testSetMethodArguments().
     */
    public function testSetMethodArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::getMethodArgument
     * @todo   Implement testGetMethodArgument().
     */
    public function testGetMethodArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::hasMethodArgument
     * @todo   Implement testHasMethodArgument().
     */
    public function testHasMethodArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::addMethodArgument
     * @todo   Implement testAddMethodArgument().
     */
    public function testAddMethodArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::setMethodArgument
     * @todo   Implement testSetMethodArgument().
     */
    public function testSetMethodArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::isUnique
     * @todo   Implement testIsUnique().
     */
    public function testIsUnique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CSanquer\FakeryGenerator\Model\VariableConfig::setUnique
     * @todo   Implement testSetUnique().
     */
    public function testSetUnique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}

